orekit:
  data-path: src/main/resources/orekit-data

orekit-update:
  bash: "C:/Program Files/Git/bin/bash.exe"

spring:
  application:
    name : SatTool
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  output:
    ansi:
      enabled: ALWAYS